name: build-and-push-docker-image
 
on:
 push:
   branches: dev
 
jobs:
 main:
   runs-on: ubuntu-20.04
   steps:
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.ANDRO_SEC_TEST_DOCKERHUB_TOKEN }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: shostarson/androsectest:latest
